version: "3"

services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
        - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - /etc/letsencrypt/live/keycloak.credio.xyz/fullchain.pem:/root/ssl/localhost.crt
        - /etc/letsencrypt/live/keycloak.credio.xyz/privkey.pem:/root/ssl/localhost.key
    ports:
        - "80:80"
        - "443:443"
    depends_on:
      - keycloak    